# Generated by Django 3.0.5 on 2020-05-03 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaching_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='tag',
        ),
        migrations.AddField(
            model_name='student',
            name='tag',
            field=models.ManyToManyField(to='coaching_app.Tag'),
        ),
    ]
