# Generated by Django 3.0.5 on 2020-05-21 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaching_app', '0004_auto_20200503_2313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='coach',
        ),
        migrations.RemoveField(
            model_name='room',
            name='student',
        ),
        migrations.AddField(
            model_name='room',
            name='student',
            field=models.ManyToManyField(to='coaching_app.Student'),
        ),
    ]
