# Generated by Django 3.0.5 on 2020-05-21 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coaching_app', '0005_auto_20200521_1346'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Room',
            new_name='Team',
        ),
    ]
