# Generated by Django 3.0.5 on 2020-05-21 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaching_app', '0006_auto_20200521_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='coach',
            field=models.ManyToManyField(to='coaching_app.Coach'),
        ),
    ]
