# Generated by Django 3.0.5 on 2020-05-28 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaching_app', '0009_team_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statname', models.CharField(max_length=200)),
                ('statvalue', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='stat',
            field=models.ManyToManyField(to='coaching_app.Stat'),
        ),
    ]
